/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PagedModelMessageResponseDto,
} from '../models/index';
import {
    PagedModelMessageResponseDtoFromJSON,
    PagedModelMessageResponseDtoToJSON,
} from '../models/index';

export interface GetLatestMessagesRequest {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

/**
 * 
 */
export class MessageRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getLatestMessagesRaw(requestParameters: GetLatestMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelMessageResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/messages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelMessageResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getLatestMessages(requestParameters: GetLatestMessagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelMessageResponseDto> {
        const response = await this.getLatestMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
