/* tslint:disable */
/* eslint-disable */
/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MessageRequestRequestDto,
  MessageRequestResponseDto,
} from '../models/index';
import {
    MessageRequestRequestDtoFromJSON,
    MessageRequestRequestDtoToJSON,
    MessageRequestResponseDtoFromJSON,
    MessageRequestResponseDtoToJSON,
} from '../models/index';

export interface ApproveMessageRequestRequest {
    messageRequestId: string;
}

export interface CreateMessageRequestRequest {
    messageRequestRequestDto: MessageRequestRequestDto;
}

export interface GetMessageRequestRequest {
    messageRequestId: string;
}

/**
 * 
 */
export class MessageRequestRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async approveMessageRequestRaw(requestParameters: ApproveMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageRequestResponseDto>> {
        if (requestParameters['messageRequestId'] == null) {
            throw new runtime.RequiredError(
                'messageRequestId',
                'Required parameter "messageRequestId" was null or undefined when calling approveMessageRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/message-requests/{message_request_id}/approve`.replace(`{${"message_request_id"}}`, encodeURIComponent(String(requestParameters['messageRequestId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageRequestResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async approveMessageRequest(requestParameters: ApproveMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageRequestResponseDto> {
        const response = await this.approveMessageRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createMessageRequestRaw(requestParameters: CreateMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageRequestResponseDto>> {
        if (requestParameters['messageRequestRequestDto'] == null) {
            throw new runtime.RequiredError(
                'messageRequestRequestDto',
                'Required parameter "messageRequestRequestDto" was null or undefined when calling createMessageRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/message-requests/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageRequestRequestDtoToJSON(requestParameters['messageRequestRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageRequestResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async createMessageRequest(requestParameters: CreateMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageRequestResponseDto> {
        const response = await this.createMessageRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMessageRequestRaw(requestParameters: GetMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageRequestResponseDto>> {
        if (requestParameters['messageRequestId'] == null) {
            throw new runtime.RequiredError(
                'messageRequestId',
                'Required parameter "messageRequestId" was null or undefined when calling getMessageRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/message-requests/{message_request_id}`.replace(`{${"message_request_id"}}`, encodeURIComponent(String(requestParameters['messageRequestId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageRequestResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getMessageRequest(requestParameters: GetMessageRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageRequestResponseDto> {
        const response = await this.getMessageRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
