// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries:
      { key: "AuthController.getAuthUser", input: never, result: UserResponseDto } |
      { key: "GroupController.getGroup", input: string, result: GroupResponseDto } |
      { key: "GroupController.getGroupMessages", input: string, result: MessageResponseDto[] } |
      { key: "MessageController.getMessages", input: never, result: MessageWithGroupResponseDto[] } |
      { key: "MessageRequestController.getMessageRequest", input: string, result: MessageRequestResponseDto } |
      { key: "UserController.getUser", input: string, result: UserResponseDto } |
      { key: "version", input: never, result: string },
    mutations:
      { key: "GroupController.createGroupMessage", input: [string, MessageRequestDto], result: MessageResponseDto } |
      { key: "MessageRequestController.approveMessageRequest", input: string, result: MessageRequestResponseDto } |
      { key: "MessageRequestController.createMessageRequest", input: MessageRequestRequestDto, result: MessageRequestResponseDto } |
      { key: "UserController.createUser", input: UserRequestDto, result: UserResponseDto } |
      { key: "UserPushSubscriptionController.createUserPushSubscription", input: UserPushSubscriptionRequestDto, result: UserPushSubscriptionResponseDto },
    subscriptions: never
};

export type MessageWithGroupResponseDto = { id: string; createdAt: string; updatedAt: string; group: GroupResponseDto; source: UserResponseDto; content: string; idempotencyKey: string | null }

export type MessageRequestRequestDto = { destinationId: string }

export type GroupResponseDto = { id: string; createdAt: string; updatedAt: string; name: string; messageRequestId: string | null; users: UserResponseDto[] }

export type MessageResponseDto = { id: string; createdAt: string; updatedAt: string; source: UserResponseDto; content: string; idempotencyKey: string | null }

export type UserRequestDto = { publicKey: string }

export type MessageRequestDto = { content: { [key: string]: string }; idempotencyKey: string | null }

export type UserPushSubscriptionResponseDto = { id: string; createdAt: string; updatedAt: string; userId: string; endpoint: string; p256Dh: string; auth: string }

export type UserPushSubscriptionRequestDto = { endpoint: string; p256Dh: string; auth: string }

export type UserResponseDto = { id: string; createdAt: string; updatedAt: string; name: string; publicKey: string }

export type MessageRequestResponseDto = { id: string; createdAt: string; updatedAt: string; source: UserResponseDto; destination: UserResponseDto; approvedAt: string | null }
