// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries:
      { key: "auth.getAuthUser", input: never, result: UserResponseDto } |
      { key: "groups.getGroup", input: string, result: GroupResponseDto } |
      { key: "groups.getGroupMessages", input: string, result: MessageResponseDto[] } |
      { key: "messageRequests.getMessageRequest", input: string, result: MessageRequestResponseDto } |
      { key: "messages.getMessages", input: never, result: MessageWithGroupResponseDto[] } |
      { key: "users.getUser", input: string, result: UserResponseDto } |
      { key: "version", input: never, result: string },
    mutations:
      { key: "groups.createGroupMessage", input: [string, MessageRequestDto], result: MessageResponseDto } |
      { key: "messageRequests.approveMessageRequest", input: string, result: MessageRequestResponseDto } |
      { key: "messageRequests.createMessageRequest", input: MessageRequestRequestDto, result: MessageRequestResponseDto } |
      { key: "userPushSubscriptions.createUserPushSubscription", input: UserPushSubscriptionRequestDto, result: UserPushSubscriptionResponseDto } |
      { key: "users.createUser", input: UserRequestDto, result: UserResponseDto } |
      { key: "users.createUserProfilePicturePresignedUploadUrl", input: PresignedUploadUrlRequestDto, result: PresignedUploadUrlResponseDto },
    subscriptions:
      { key: "messages.subscribeToMessages", input: never, result: MessageWithGroupResponseDto | null }
};

export type MessageWithGroupResponseDto = { id: string; createdAt: string; updatedAt: string; group: GroupResponseDto; source: UserResponseDto; content: string; idempotencyKey: string | null }

export type MessageRequestRequestDto = { destinationId: string }

export type PresignedUploadUrlRequestDto = { contentType: string }

export type GroupResponseDto = { id: string; createdAt: string; updatedAt: string; name: string; messageRequestId: string | null; users: UserResponseDto[] }

export type PresignedUploadUrlResponseDto = { url: string }

export type MessageResponseDto = { id: string; createdAt: string; updatedAt: string; source: UserResponseDto; content: string; idempotencyKey: string | null }

export type UserRequestDto = { publicKey: string }

export type MessageRequestDto = { content: { [key: string]: string }; idempotencyKey: string | null }

export type UserPushSubscriptionResponseDto = { id: string; createdAt: string; updatedAt: string; userId: string; endpoint: string; p256dh: string; auth: string }

export type UserPushSubscriptionRequestDto = { endpoint: string; p256dh: string; auth: string }

export type UserResponseDto = { id: string; createdAt: string; updatedAt: string; name: string; publicKey: string }

export type MessageRequestResponseDto = { id: string; createdAt: string; updatedAt: string; source: UserResponseDto; destination: UserResponseDto; approvedAt: string | null }
