/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupResponseDtoUsersInner
 */
export interface GroupResponseDtoUsersInner {
    /**
     * 
     * @type {Date}
     * @memberof GroupResponseDtoUsersInner
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GroupResponseDtoUsersInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GroupResponseDtoUsersInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupResponseDtoUsersInner
     */
    publicKey: string;
    /**
     * 
     * @type {Date}
     * @memberof GroupResponseDtoUsersInner
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the GroupResponseDtoUsersInner interface.
 */
export function instanceOfGroupResponseDtoUsersInner(value: object): value is GroupResponseDtoUsersInner {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GroupResponseDtoUsersInnerFromJSON(json: any): GroupResponseDtoUsersInner {
    return GroupResponseDtoUsersInnerFromJSONTyped(json, false);
}

export function GroupResponseDtoUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupResponseDtoUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'name': json['name'],
        'publicKey': json['publicKey'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function GroupResponseDtoUsersInnerToJSON(value?: GroupResponseDtoUsersInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': ((value['createdAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'publicKey': value['publicKey'],
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

