/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface GroupUsers
 */
export interface GroupUsers {
    /**
     * 
     * @type {string}
     * @memberof GroupUsers
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GroupUsers
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GroupUsers
     */
    updatedAt: Date;
    /**
     * 
     * @type {Group}
     * @memberof GroupUsers
     */
    group: Group;
    /**
     * 
     * @type {User}
     * @memberof GroupUsers
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof GroupUsers
     */
    nickname?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GroupUsers
     */
    admin?: boolean;
}

/**
 * Check if a given object implements the GroupUsers interface.
 */
export function instanceOfGroupUsers(value: object): value is GroupUsers {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GroupUsersFromJSON(json: any): GroupUsers {
    return GroupUsersFromJSONTyped(json, false);
}

export function GroupUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUsers {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'group': GroupFromJSON(json['group']),
        'user': UserFromJSON(json['user']),
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'admin': json['admin'] == null ? undefined : json['admin'],
    };
}

export function GroupUsersToJSON(value?: GroupUsers | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'group': GroupToJSON(value['group']),
        'user': UserToJSON(value['user']),
        'nickname': value['nickname'],
        'admin': value['admin'],
    };
}

