/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageUserRequestDto
 */
export interface MessageUserRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MessageUserRequestDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof MessageUserRequestDto
     */
    userId: string;
}

/**
 * Check if a given object implements the MessageUserRequestDto interface.
 */
export function instanceOfMessageUserRequestDto(value: object): value is MessageUserRequestDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function MessageUserRequestDtoFromJSON(json: any): MessageUserRequestDto {
    return MessageUserRequestDtoFromJSONTyped(json, false);
}

export function MessageUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUserRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'userId': json['userId'],
    };
}

export function MessageUserRequestDtoToJSON(value?: MessageUserRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'userId': value['userId'],
    };
}

