/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface MessageUser
 */
export interface MessageUser {
    /**
     * 
     * @type {string}
     * @memberof MessageUser
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MessageUser
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MessageUser
     */
    updatedAt: Date;
    /**
     * 
     * @type {User}
     * @memberof MessageUser
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof MessageUser
     */
    content: string;
}

/**
 * Check if a given object implements the MessageUser interface.
 */
export function instanceOfMessageUser(value: object): value is MessageUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function MessageUserFromJSON(json: any): MessageUser {
    return MessageUserFromJSONTyped(json, false);
}

export function MessageUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'user': UserFromJSON(json['user']),
        'content': json['content'],
    };
}

export function MessageUserToJSON(value?: MessageUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'user': UserToJSON(value['user']),
        'content': value['content'],
    };
}

