/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageRequestDto
 */
export interface MessageRequestDto {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MessageRequestDto
     */
    content: { [key: string]: string; };
}

/**
 * Check if a given object implements the MessageRequestDto interface.
 */
export function instanceOfMessageRequestDto(value: object): value is MessageRequestDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function MessageRequestDtoFromJSON(json: any): MessageRequestDto {
    return MessageRequestDtoFromJSONTyped(json, false);
}

export function MessageRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function MessageRequestDtoToJSON(value?: MessageRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
    };
}

