/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface MessageRequest
 */
export interface MessageRequest {
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MessageRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MessageRequest
     */
    updatedAt: Date;
    /**
     * 
     * @type {User}
     * @memberof MessageRequest
     */
    source?: User;
    /**
     * 
     * @type {User}
     * @memberof MessageRequest
     */
    destination?: User;
    /**
     * 
     * @type {Date}
     * @memberof MessageRequest
     */
    approvedAt?: Date;
}

/**
 * Check if a given object implements the MessageRequest interface.
 */
export function instanceOfMessageRequest(value: object): value is MessageRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MessageRequestFromJSON(json: any): MessageRequest {
    return MessageRequestFromJSONTyped(json, false);
}

export function MessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'source': json['source'] == null ? undefined : UserFromJSON(json['source']),
        'destination': json['destination'] == null ? undefined : UserFromJSON(json['destination']),
        'approvedAt': json['approvedAt'] == null ? undefined : (new Date(json['approvedAt'])),
    };
}

export function MessageRequestToJSON(value?: MessageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'source': UserToJSON(value['source']),
        'destination': UserToJSON(value['destination']),
        'approvedAt': value['approvedAt'] == null ? undefined : ((value['approvedAt']).toISOString()),
    };
}

