/* tslint:disable */
/* eslint-disable */
/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
} from './UserResponseDto';

/**
 * 
 * @export
 * @interface MessageResponseDto
 */
export interface MessageResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    idempotencyKey?: string | null;
    /**
     * 
     * @type {UserResponseDto}
     * @memberof MessageResponseDto
     */
    source: UserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MessageResponseDto interface.
 */
export function instanceOfMessageResponseDto(value: object): value is MessageResponseDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MessageResponseDtoFromJSON(json: any): MessageResponseDto {
    return MessageResponseDtoFromJSONTyped(json, false);
}

export function MessageResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'createdAt': json['createdAt'],
        'id': json['id'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'source': UserResponseDtoFromJSON(json['source']),
        'updatedAt': json['updatedAt'],
    };
}

export function MessageResponseDtoToJSON(value?: MessageResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'idempotencyKey': value['idempotencyKey'],
        'source': UserResponseDtoToJSON(value['source']),
        'updatedAt': value['updatedAt'],
    };
}

