/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupResponseDtoUsersInner } from './GroupResponseDtoUsersInner';
import {
    GroupResponseDtoUsersInnerFromJSON,
    GroupResponseDtoUsersInnerFromJSONTyped,
    GroupResponseDtoUsersInnerToJSON,
} from './GroupResponseDtoUsersInner';

/**
 * 
 * @export
 * @interface MessageRequestResponseDto
 */
export interface MessageRequestResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof MessageRequestResponseDto
     */
    approvedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MessageRequestResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {GroupResponseDtoUsersInner}
     * @memberof MessageRequestResponseDto
     */
    destination: GroupResponseDtoUsersInner;
    /**
     * 
     * @type {string}
     * @memberof MessageRequestResponseDto
     */
    id: string;
    /**
     * 
     * @type {GroupResponseDtoUsersInner}
     * @memberof MessageRequestResponseDto
     */
    source: GroupResponseDtoUsersInner;
    /**
     * 
     * @type {Date}
     * @memberof MessageRequestResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the MessageRequestResponseDto interface.
 */
export function instanceOfMessageRequestResponseDto(value: object): value is MessageRequestResponseDto {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MessageRequestResponseDtoFromJSON(json: any): MessageRequestResponseDto {
    return MessageRequestResponseDtoFromJSONTyped(json, false);
}

export function MessageRequestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequestResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'approvedAt': json['approvedAt'] == null ? undefined : (new Date(json['approvedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'destination': GroupResponseDtoUsersInnerFromJSON(json['destination']),
        'id': json['id'],
        'source': GroupResponseDtoUsersInnerFromJSON(json['source']),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function MessageRequestResponseDtoToJSON(value?: MessageRequestResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'approvedAt': value['approvedAt'] == null ? undefined : ((value['approvedAt']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'destination': GroupResponseDtoUsersInnerToJSON(value['destination']),
        'id': value['id'],
        'source': GroupResponseDtoUsersInnerToJSON(value['source']),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

