/* tslint:disable */
/* eslint-disable */
/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
} from './UserResponseDto';
import type { GroupResponseDto } from './GroupResponseDto';
import {
    GroupResponseDtoFromJSON,
    GroupResponseDtoFromJSONTyped,
    GroupResponseDtoToJSON,
} from './GroupResponseDto';

/**
 * 
 * @export
 * @interface MessageWithGroupResponseDto
 */
export interface MessageWithGroupResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageWithGroupResponseDto
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof MessageWithGroupResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {GroupResponseDto}
     * @memberof MessageWithGroupResponseDto
     */
    group: GroupResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageWithGroupResponseDto
     */
    id: string;
    /**
     * 
     * @type {UserResponseDto}
     * @memberof MessageWithGroupResponseDto
     */
    source: UserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageWithGroupResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MessageWithGroupResponseDto interface.
 */
export function instanceOfMessageWithGroupResponseDto(value: object): value is MessageWithGroupResponseDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MessageWithGroupResponseDtoFromJSON(json: any): MessageWithGroupResponseDto {
    return MessageWithGroupResponseDtoFromJSONTyped(json, false);
}

export function MessageWithGroupResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageWithGroupResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'createdAt': json['createdAt'],
        'group': GroupResponseDtoFromJSON(json['group']),
        'id': json['id'],
        'source': UserResponseDtoFromJSON(json['source']),
        'updatedAt': json['updatedAt'],
    };
}

export function MessageWithGroupResponseDtoToJSON(value?: MessageWithGroupResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'createdAt': value['createdAt'],
        'group': GroupResponseDtoToJSON(value['group']),
        'id': value['id'],
        'source': UserResponseDtoToJSON(value['source']),
        'updatedAt': value['updatedAt'],
    };
}

