/* tslint:disable */
/* eslint-disable */
/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponseDto } from './UserResponseDto';
import {
    UserResponseDtoFromJSON,
    UserResponseDtoFromJSONTyped,
    UserResponseDtoToJSON,
} from './UserResponseDto';

/**
 * 
 * @export
 * @interface MessageRequestResponseDto
 */
export interface MessageRequestResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageRequestResponseDto
     */
    approvedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MessageRequestResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {UserResponseDto}
     * @memberof MessageRequestResponseDto
     */
    destination: UserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageRequestResponseDto
     */
    id: string;
    /**
     * 
     * @type {UserResponseDto}
     * @memberof MessageRequestResponseDto
     */
    source: UserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageRequestResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the MessageRequestResponseDto interface.
 */
export function instanceOfMessageRequestResponseDto(value: object): value is MessageRequestResponseDto {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MessageRequestResponseDtoFromJSON(json: any): MessageRequestResponseDto {
    return MessageRequestResponseDtoFromJSONTyped(json, false);
}

export function MessageRequestResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequestResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'approvedAt': json['approvedAt'] == null ? undefined : json['approvedAt'],
        'createdAt': json['createdAt'],
        'destination': UserResponseDtoFromJSON(json['destination']),
        'id': json['id'],
        'source': UserResponseDtoFromJSON(json['source']),
        'updatedAt': json['updatedAt'],
    };
}

export function MessageRequestResponseDtoToJSON(value?: MessageRequestResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'approvedAt': value['approvedAt'],
        'createdAt': value['createdAt'],
        'destination': UserResponseDtoToJSON(value['destination']),
        'id': value['id'],
        'source': UserResponseDtoToJSON(value['source']),
        'updatedAt': value['updatedAt'],
    };
}

