/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageRequestRequestDto
 */
export interface MessageRequestRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MessageRequestRequestDto
     */
    destinationId: string;
}

/**
 * Check if a given object implements the MessageRequestRequestDto interface.
 */
export function instanceOfMessageRequestRequestDto(value: object): value is MessageRequestRequestDto {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    return true;
}

export function MessageRequestRequestDtoFromJSON(json: any): MessageRequestRequestDto {
    return MessageRequestRequestDtoFromJSONTyped(json, false);
}

export function MessageRequestRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequestRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
    };
}

export function MessageRequestRequestDtoToJSON(value?: MessageRequestRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'destinationId': value['destinationId'],
    };
}

