/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageUserResponseDto
 */
export interface MessageUserResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageUserResponseDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessageUserResponseDto
     */
    name: string;
}

/**
 * Check if a given object implements the MessageUserResponseDto interface.
 */
export function instanceOfMessageUserResponseDto(value: object): value is MessageUserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MessageUserResponseDtoFromJSON(json: any): MessageUserResponseDto {
    return MessageUserResponseDtoFromJSONTyped(json, false);
}

export function MessageUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function MessageUserResponseDtoToJSON(value?: MessageUserResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

