/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageUserResponseDto } from './MessageUserResponseDto';
import {
    MessageUserResponseDtoFromJSON,
    MessageUserResponseDtoFromJSONTyped,
    MessageUserResponseDtoToJSON,
} from './MessageUserResponseDto';

/**
 * 
 * @export
 * @interface MessageResponseDto
 */
export interface MessageResponseDto {
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MessageResponseDto
     */
    createdAt: Date;
    /**
     * 
     * @type {MessageUserResponseDto}
     * @memberof MessageResponseDto
     */
    user: MessageUserResponseDto;
    /**
     * 
     * @type {string}
     * @memberof MessageResponseDto
     */
    content: string;
}

/**
 * Check if a given object implements the MessageResponseDto interface.
 */
export function instanceOfMessageResponseDto(value: object): value is MessageResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function MessageResponseDtoFromJSON(json: any): MessageResponseDto {
    return MessageResponseDtoFromJSONTyped(json, false);
}

export function MessageResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'user': MessageUserResponseDtoFromJSON(json['user']),
        'content': json['content'],
    };
}

export function MessageResponseDtoToJSON(value?: MessageResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'user': MessageUserResponseDtoToJSON(value['user']),
        'content': value['content'],
    };
}

