/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
} from './PageMetadata';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface PagedModelMessage
 */
export interface PagedModelMessage {
    /**
     * 
     * @type {Array<Message>}
     * @memberof PagedModelMessage
     */
    content?: Array<Message>;
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelMessage
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelMessage interface.
 */
export function instanceOfPagedModelMessage(value: object): value is PagedModelMessage {
    return true;
}

export function PagedModelMessageFromJSON(json: any): PagedModelMessage {
    return PagedModelMessageFromJSONTyped(json, false);
}

export function PagedModelMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(MessageFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelMessageToJSON(value?: PagedModelMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(MessageToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

